# Use an official Nginx image as the base image
FROM nginx:latest

# Copy the contents of the local 'web' directory to the Nginx document root
COPY web/ /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80

# Command to start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]
